// AUTO-GENERATED by scripts/generate-image-manifest.mjs
// Do not edit manually. Run: npm run images

export interface ProjectImages {
  folder: string;
  count: number;
  thumbnail: string | null;
  images: string[];
}

export const projectImages: Record<string, ProjectImages> = {
  'Achievements': {
    folder: '/images/achievements_mind2flow',
    count: 2,
    thumbnail: '/images/achievements_mind2flow/WhatsApp Image 2026-06-02 at 10.55.18 PM.jpeg',
    images: [
      '/images/achievements_mind2flow/WhatsApp Image 2026-06-02 at 10.55.18 PM.jpeg',
      '/images/achievements_mind2flow/WhatsApp Image 2026-06-02 at 10.56.49 PM.jpeg',
    ],
  },
  'AURA': {
    folder: '/images/aura',
    count: 4,
    thumbnail: '/images/aura/WhatsApp Image 2026-06-02 at 9.15.27 PM.jpeg',
    images: [
      '/images/aura/WhatsApp Image 2026-06-02 at 9.15.27 PM.jpeg',
      '/images/aura/WhatsApp Image 2026-06-02 at 9.23.03 PM.jpeg',
      '/images/aura/WhatsApp Image 2026-06-02 at 9.23.24 PM.jpeg',
      '/images/aura/WhatsApp Image 2026-06-02 at 9.24.11 PM.jpeg',
    ],
  },
  'ChronoCancer AI': {
    folder: '/images/chronocancer',
    count: 8,
    thumbnail: '/images/chronocancer/FIRST.jpeg',
    images: [
      '/images/chronocancer/FIRST.jpeg',
      '/images/chronocancer/Screenshot 2026-06-02 222901.png',
      '/images/chronocancer/Screenshot 2026-06-02 222907.png',
      '/images/chronocancer/Screenshot 2026-06-02 222916.png',
      '/images/chronocancer/WhatsApp Image 2026-06-02 at 10.25.20 PM.jpeg',
      '/images/chronocancer/WhatsApp Image 2026-06-02 at 10.25.22 PM.jpeg',
      '/images/chronocancer/WhatsApp Image 2026-06-02 at 10.25.23 PM.jpeg',
      '/images/chronocancer/WhatsApp Image 2026-06-02 at 10.25.24 PM.jpeg',
    ],
  },
  'GlamSpot': {
    folder: '/images/glam',
    count: 0,
    thumbnail: null,
    images: [
    ],
  },
  'Noble Classes': {
    folder: '/images/noble classes',
    count: 3,
    thumbnail: '/images/noble classes/Screenshot 2026-07-14 031825.png',
    images: [
      '/images/noble classes/Screenshot 2026-07-14 031825.png',
      '/images/noble classes/Screenshot 2026-07-14 031902.png',
      '/images/noble classes/Screenshot 2026-07-14 032006.png',
    ],
  },
  'Pet Clinic': {
    folder: '/images/petclinic',
    count: 4,
    thumbnail: '/images/petclinic/Screenshot 2026-07-14 024512.png',
    images: [
      '/images/petclinic/Screenshot 2026-07-14 024512.png',
      '/images/petclinic/Screenshot 2026-07-14 024522.png',
      '/images/petclinic/Screenshot 2026-07-14 024548.png',
      '/images/petclinic/Screenshot 2026-07-14 024633.png',
    ],
  },
  'Prvaas': {
    folder: '/images/pravaas',
    count: 4,
    thumbnail: '/images/pravaas/Screenshot 2026-07-14 025025.png',
    images: [
      '/images/pravaas/Screenshot 2026-07-14 025025.png',
      '/images/pravaas/Screenshot 2026-07-14 025049.png',
      '/images/pravaas/Screenshot 2026-07-14 025144.png',
      '/images/pravaas/Screenshot 2026-07-14 025153.png',
    ],
  },
  'SkillLab': {
    folder: '/images/skill_lab',
    count: 6,
    thumbnail: '/images/skill_lab/Screenshot 2026-06-02 224339.png',
    images: [
      '/images/skill_lab/Screenshot 2026-06-02 224339.png',
      '/images/skill_lab/Screenshot 2026-06-02 224350.png',
      '/images/skill_lab/Screenshot 2026-06-02 224358.png',
      '/images/skill_lab/Screenshot 2026-06-02 224439.png',
      '/images/skill_lab/Screenshot 2026-06-02 224509.png',
      '/images/skill_lab/Screenshot 2026-06-02 224521.png',
    ],
  },
  'ZipDrop': {
    folder: '/images/zipdrop',
    count: 2,
    thumbnail: '/images/zipdrop/Screenshot 2026-06-02 222150.png',
    images: [
      '/images/zipdrop/Screenshot 2026-06-02 222150.png',
      '/images/zipdrop/Screenshot 2026-06-02 222240.png',
    ],
  },
};
